### ISSUE TITLE
Windows Batch File 9x/ME Preferred Cmdline Executing @WinNT Error(실행 배치파일에서 9x나 ME용 구문이 WinNT에서도 실행되는 오류)

### ISSUE THREAD

**Issue by HotoRas** [noonmaru/parkour-maker#1]
(모르겠다 내용은 한국업니다)
Windows NT에서는 9x/ME 파트가 스킵되노록 되어있어야 하는데
중간에
`if not %OS% == "Windows_NT" goto win9xME_args` 뒤에 해당구문이 정의되어있어서 cmd의 처리 구조(순차식)상 NT에서도 해당 구문이 실행되는 오류가 있습니다.
저 부분에 이어서
` else goto execute` 집어넣으면 해결될 것 같습니다.
-유투브 구독자

**Comment by HotoRas** [comment]
참고로 /parkour-maker/gradlew.bat의 51번째 줄에 있습니다.

**Comment by HotoRas** [comment]
이거 그냥 닫아둘게요
딴거에서도 똑같은 거 보니까 문제는 없을 듯 하네요

**Comment by M4R1O64** [comment]
이거 어케 서버 열어요 그리고 어케 적용해요?

**Comment by patrick-choe** [comment]
> (모르겠다 내용은 한국업니다)
> Windows NT에서는 9x/ME 파트가 스킵되노록 되어있어야 하는데
> 중간에
> `if not %OS% == "Windows_NT" goto win9xME_args` 뒤에 해당구문이 정의되어있어서 cmd의 처리 구조(순차식)상 NT에서도 해당 구문이 실행되는 오류가 있습니다.
> 저 부분에 이어서
> ` else goto execute` 집어넣으면 해결될 것 같습니다.
> -유투브 구독자

@JeonDohyeon gradlew.bat은 gradle 프로젝트를 만들면 자동으로 생성되는 파일이며, noonmaru님이 쓴 부분이 아닙니다.  gradlew.bat은 gradle을 사용하는 모든 프로젝트에 기본 생성되는 파일이므로 문제 없을겁니다..

**Comment by M4R1O64** [comment]
님들 이거 어케 해요?

**Comment by HotoRas** [comment]
> > (모르겠다 내용은 한국업니다)
> > Windows NT에서는 9x/ME 파트가 스킵되노록 되어있어야 하는데
> > 중간에
> > `if not %OS% == "Windows_NT" goto win9xME_args` 뒤에 해당구문이 정의되어있어서 cmd의 처리 구조(순차식)상 NT에서도 해당 구문이 실행되는 오류가 있습니다.
> > 저 부분에 이어서
> > ` else goto execute` 집어넣으면 해결될 것 같습니다.
> > -유투브 구독자
> 
> @JeonDohyeon gradlew.bat은 gradle 프로젝트를 만들면 자동으로 생성되는 파일이며, noonmaru님이 쓴 부분이 아닙니다. gradlew.bat은 gradle을 사용하는 모든 프로젝트에 기본 생성되는 파일이므로 문제 없을겁니다..

@patrick-mc 감사합니다. 이건 몰랐던 부분이네요.
