### ISSUE TITLE
jar파일은 어디서 구해야 하나요?

### ISSUE THREAD

**Issue by hitog** [noonmaru/parkour-maker#21]
압축파일로만 다운이 됩니다 jar은 어디서 구해야 하나요?

**Comment by ghost** [comment]
나와있는 내용으로만 이해가 가능한게 압축 프로그램이 .jar 확장자로 여는걸 차지하는거 같네요.

Java로 열리게 하시면됩니다.

**Comment by hitog** [comment]
그게아니라 다운로드를 어떻게 해야 하나요 지금 저는 다운로드 코드에서 압축파일로만 다운할수 밖에 없는데 제가 잘못하고있는 건지 궁금해서요

**Comment by ghost** [comment]
아 제가 잘못이해했군요

[현재 있는 코드](https://github.com/noonmaru/parkour-maker/archive/master.zip)를 빌드하셔서 사용하시면 됩니다.

빌드방법은 #2 에 쓰인 [댓글](https://github.com/noonmaru/parkour-maker/issues/2#issuecomment-603676064)을 참고해주세요.
+ 의존성 플러그인도 받으셔야합니다.

OpenJDK 8이나 11쪽 사용을 권장합니다.

**Comment by ghost** [comment]
- 서버 구동
---
> [Paper 1.16.1](https://papermc.io/api/v1/paper/1.16.1/latest/download)
---
- 의존성 플러그인
---
> [Tap 2.8.8](https://github.com/noonmaru/tap/releases/download/2.8.8/tap-2.8.8-dist.jar)
> [WorldEdit 7.1.0](https://dev.bukkit.org/projects/worldedit/files/2869453/download)
> [ProtocolLib 4.6.0](https://ci.dmulloy2.net/job/ProtocolLib/) (작성시간 기준 서버가 죽어있네요... 조금있다가 확인해보시길)
> [Kotlin 1.3.72](https://github.com/noonmaru/kotlin-plugin/releases/download/1.3.72/kotlin-1.3.72-lib.jar)
---

**Comment by hitog** [comment]
어떻게 구축하나요?

**Comment by hitog** [comment]
댓글 보고 따라해봤는데 tap parkour-maker jar로 바꾸는게 조금 어렵네요 어떻게 해야해나요?

**Comment by devil0414** [comment]
gradlew clean distJar명령어를 실행하시면 됩니더

**Comment by ghost** [comment]
> gradlew clean distJar명령어를 실행하시면 됩니다

참고로 Tap은 릴리즈 링크를 이미 올려드렸기에 상관없습니다. @hitog

**Comment by hitog** [comment]
> gradlew clean distJar명령어를 실행하시면 됩니다

어디에다 입력하나요?

**Comment by devil0414** [comment]
터미널에 입력하세요

**Comment by devil0414** [comment]
터미널을 이용해 소스코드로 경로 지정 후 명령어를 실행하시면 됩니다.

**Comment by devil0414** [comment]
#2 참고하세요

**Comment by hitog** [comment]
> 터미널을 이용해 소스코드로 경로 지정 후 명령어를 실행하시면 됩니다.
> 
> 명령어 실향하기 전에 반드시 build.gradle.kts를 수정해야 합니다.

제가 무작정 플러그인에 뛰어든 초보라 조금만 더 쉽게 말해주실 수 있나요? 
도와주느라 감사합니다ㅠㅠ

**Comment by hitog** [comment]
> 터미널을 이용해 소스코드로 경로 지정 후 명령어를 실행하시면 됩니다.
> 명령어 실향하기 전에 반드시 build.gradle.kts를 수정해야 합니다.

터미널이 뭐죠?

**Comment by ghost** [comment]
build.gradle.kts를 메모장이나 워드패드로 여시고
```kotlin
create<Copy>("distJar") {
        from(shadowJar)
        into("W:\\Servers\\parkour-maker\\plugins")
    }
```
를
```kotlin
create<Copy>("distJar") {
        from(shadowJar)
        into(".\\") // 작업을 실행하는 디렉터리 내에 바로 .jar를 만듭니다.
    }
```
로 바꿔주시고 저장하세요.

빌드를 할 차례입니다.
윈도우 체계이신경우 그 폴더 내에서 Shift + 우클릭을 누른뒤 PowerShell을 열어주세요.

이후 `.\gradlew clean distJar`를 입력하여 빌드하시면 됩니다.

빌드 하시기 전에 JDK를 설치하시고 JAVA_HOME을 설정해주세요. (방법은 구글링 하면 다 나옵니다. JDK는 8을 권장합니다.)

**Comment by hitog** [comment]
감사합니다

**Comment by hitog** [comment]
파워셀 부분에서 빌드가 실패했다고 뜨네요 어떻게 해야하나요?

**Comment by hitog** [comment]
빌드 실패했다고 자꾸 뜨는데 뭐가 잘못됐을까요?

**Comment by hitog** [comment]
됐는데 이제 어떻게 해야하나요?

**Comment by hitog** [comment]
덕분에 해결했어요! 감사합니다!

**Comment by devil0414** [comment]
이제 이슈 닫아주세요
