### ISSUE TITLE
빌드문제

### ISSUE THREAD

**Issue by chipppppp** [noonmaru/parkour-maker#22]
저만파쿠르메이커만빌드안되나요다른플러그인은다빌드되는데파쿠르메이커만빌드가안되서...

**Comment by chipppppp** [comment]
> 저만 파 쿠르 메이커 만 빌드 안되나여 다른 플러그인은 다 빌드 만파 쿠르 메이커 빌드가 안되서 ...

**Comment by chipppppp** [comment]
* What went wrong:
Execution failed for task ':compileKotlin'.
> Could not resolve all files for configuration ':compileClasspath'.
   > Could not find com.comphenix.protocol:ProtocolLib:4.6.0-SNAPSHOT.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/com/comphenix/protocol/ProtocolLib/4.6.0-SNAPSHOT/maven-metadata.xml
       - https://repo.maven.apache.org/maven2/com/comphenix/protocol/ProtocolLib/4.6.0-SNAPSHOT/ProtocolLib-4.6.0-SNAPSHOT.pom
       - https://repo.maven.apache.org/maven2/com/comphenix/protocol/ProtocolLib/4.6.0-SNAPSHOT/ProtocolLib-4.6.0-SNAPSHOT.jar
       - https://papermc.io/repo/repository/maven-public/com/comphenix/protocol/ProtocolLib/4.6.0-SNAPSHOT/maven-metadata.xml
       - https://papermc.io/repo/repository/maven-public/com/comphenix/protocol/ProtocolLib/4.6.0-SNAPSHOT/ProtocolLib-4.6.0-SNAPSHOT.pom
       - https://papermc.io/repo/repository/maven-public/com/comphenix/protocol/ProtocolLib/4.6.0-SNAPSHOT/ProtocolLib-4.6.0-SNAPSHOT.jar
       - https://repo.dmulloy2.net/nexus/repository/public/com/comphenix/protocol/ProtocolLib/4.6.0-SNAPSHOT/maven-metadata.xml
       - https://repo.dmulloy2.net/nexus/repository/public/com/comphenix/protocol/ProtocolLib/4.6.0-SNAPSHOT/ProtocolLib-4.6.0-SNAPSHOT.pom
       - https://repo.dmulloy2.net/nexus/repository/public/com/comphenix/protocol/ProtocolLib/4.6.0-SNAPSHOT/ProtocolLib-4.6.0-SNAPSHOT.jar
       - https://jitpack.io/com/comphenix/protocol/ProtocolLib/4.6.0-SNAPSHOT/maven-metadata.xml
       - https://jitpack.io/com/comphenix/protocol/ProtocolLib/4.6.0-SNAPSHOT/ProtocolLib-4.6.0-SNAPSHOT.pom
       - https://jitpack.io/com/comphenix/protocol/ProtocolLib/4.6.0-SNAPSHOT/ProtocolLib-4.6.0-SNAPSHOT.jar
       - https://maven.enginehub.org/repo/com/comphenix/protocol/ProtocolLib/4.6.0-SNAPSHOT/maven-metadata.xml
       - https://maven.enginehub.org/repo/com/comphenix/protocol/ProtocolLib/4.6.0-SNAPSHOT/ProtocolLib-4.6.0-SNAPSHOT.pom
       - https://maven.enginehub.org/repo/com/comphenix/protocol/ProtocolLib/4.6.0-SNAPSHOT/ProtocolLib-4.6.0-SNAPSHOT.jar
     Required by:
         project :

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org이렇게 뜹니다

**Comment by ghost** [comment]
ProtocolLib이 4.6.0 공식출시되고 메이븐 레포지토리에서 4.6.0-SNAPSHOT에서 4.6.0으로 변경되어서 그런듯 합니다.

**Comment by ghost** [comment]
dependencies 아래에 ProtocolLib 부분에서 `-SNAPSHOT`을 지우고 재시도 해보세요.

**Comment by chipppppp** [comment]
> 아래에 ProtocolLib 부분에서 종속성 `-SNAPSHOT`을 지우고 재시도.

감사합니다

**Comment by chipppppp** [comment]
> 아래에 ProtocolLib 부분에서 종속성 `-SNAPSHOT`을 지우고 재시도.

**Comment by chipppppp** [comment]
> 아래에 ProtocolLib 부분에서 종속성 `-SNAPSHOT`을 지우고 재시도.

더 자세히 알려주실수 있나요..

**Comment by chipppppp** [comment]
> dependencies 아래에 ProtocolLib 부분에서 `-SNAPSHOT`을 지우고 재시도 해보세요.

감사합니다

**Comment by ghost** [comment]
해결되셨다면 이슈 닫아주세요.
