### ISSUE TITLE
Tap 라이브러리 설치 관련 질문

### ISSUE THREAD

**Issue by ghost** [noonmaru/parkour-maker#5]

**Comment by ghost** [comment]
Tap 라이브러리 어떻게 설치하나요?

**Comment by wjdgustn** [comment]
https://github.com/noonmaru/parkour-maker/issues/2#issuecomment-603676064

**Comment by Apple6050** [comment]
감사합니다

**Comment by ghost** [comment]
Tap 라이브러리 clone 해서 .\gradlew shadowJar로 컴파일하니까 되네요.
