### ISSUE TITLE
Tap ./gradlew clean distJar중 나는 오류

### ISSUE THREAD

**Issue by ghost** [noonmaru/parkour-maker#7]

**Comment by ghost** [comment]
> Task :v1_13_R1:compileKotlin FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':v1_13_R1:compileKotlin'.
> Could not resolve all files for configuration ':v1_13_R1:compileClasspath'.
   > Could not resolve org.spigotmc:spigot:1.13.2-R0.1-SNAPSHOT.
     Required by:
         project :v1_13_R1
      > Could not resolve org.spigotmc:spigot:1.13.2-R0.1-SNAPSHOT.
         > Unable to load Maven meta-data from https://repo.dmulloy2.net/nexus/repository/public/org/spigotmc/spigot/1.13.2-R0.1-SNAPSHOT/maven-metadata.xml.
            > Could not get resource 'https://repo.dmulloy2.net/nexus/repository/public/org/spigotmc/spigot/1.13.2-R0.1-SNAPSHOT/maven-metadata.xml'.
               > Could not GET 'https://repo.dmulloy2.net/nexus/repository/public/org/spigotmc/spigot/1.13.2-R0.1-SNAPSHOT/maven-metadata.xml'. Received status code 500 from server: javax.servlet.ServletException: com.orientechnologies.orient.core.exception.OLowDiskSpaceException: Error occurred while executing a write operation to database 'component' due to limited free space on the disk (2956 MB). The database is now working in read-only mode. Please close the database (or stop OrientDB), make room on your hard drive and then reopen the database. The minimal required space is 4096 MB. Required space is now set to 4096MB (you can change it by setting parameter storage.diskCache.diskFreeSpaceLimit) .??        DB name="component"

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5m 53s
11 actionable tasks: 6 executed, 5 up-to-date
라고 뜨면서 빌드가 않됩니다 ㅠㅠㅠ
도와주세요

**Comment by patrick-choe** [comment]
위 프로젝트는 dmulloy 레포지토리를 사용하지 않으며, spigot 디펜던시를 가지고 있지 않습니다. 혹시 잘못 올리셨다면 해당 레포지토리에 issue 작성 바랍니다.
[build.gradle.kts](https://github.com/noonmaru/parkour-maker/blob/master/build.gradle.kts)

**Comment by ghost** [comment]
Tap에 이슈 올려야 했는데 실수했습니다 감사합니다.
